FROM golang:1.24-alpine AS builder

WORKDIR /bot

COPY go.mod go.sum ./

RUN go mod download
# RUN go install github.com/grpc-ecosystem/grpc-health-probe@v0.4.11

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o sbot ./cmd/notify/main.go

FROM gcr.io/distroless/static-debian12


WORKDIR /bot

COPY --from=builder /bot/sbot .
COPY --from=builder /bot/config/* ./config/
# COPY --from=builder /go/bin/grpc-health-probe /grpc-health-probe

EXPOSE 54822

CMD ["./sbot"]

