FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o sbot ./cmd/notify/main.go

FROM gcr.io/distroless/static-debian12


WORKDIR /notify

COPY --from=builder /app/sbot .

EXPOSE 54822

CMD ["./sbot"]

