FROM golang:1.23-alpine AS builder

WORKDIR /auth

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux -ldflags="-s -w" go build -o auth ./auth/cmd/auth/main.go

FROM gcr.io/distroless/static-debian12


WORKDIR /auth

COPY --from=builder /auth/auth .
COPY --from=builder /bot/config/* ./config/


EXPOSE 54821

CMD ["./auth"]

