apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: auth-db
  name: auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: auth-db
    spec:
      containers:
        - args:
            - postgres
            - -c
            - port=5432
            - -c
            - wal-level=logical
            - -c
            - max-wal-senders=10
            - -c
            - max-replication-slots=10
          env:
            - name: POSTGRES-DB
              value: auth
            - name: POSTGRES-PASSWORD
              value: postgres
            - name: POSTGRES-USER
              value: postgres
          image: postgres:latest
          livenessProbe:
            exec:
              command:
                - pg-isready -U postgres -p 5432
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 5
          name: auth-db
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: auth-db-cm0
              readOnly: true
            - mountPath: /var/lib/postgresql/data
              name: auth-postgres-data
      restartPolicy: Always
      volumes:
        - configMap:
            name: auth-db-cm0
          name: auth-db-cm0
        - name: auth-postgres-data
          persistentVolumeClaim:
            claimName: auth-postgres-data
