apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: auth-service
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: auth-service
    spec:
      containers:
        - env:
            - name: CODE-LIFE
              value: 10m
            - name: DB-HOST
              value: auth-db
            - name: DB-NAME
              value: auth
            - name: DB-PASSWORD
              value: postgres
            - name: DB-POOL-MAX-CONN
              value: "20"
            - name: DB-POOL-MAX-CONN-LIFETIME
              value: 2h
            - name: DB-PORT
              value: "5432"
            - name: DB-SSL-MODE
              value: disable
            - name: DB-TYPE
              value: postgres
            - name: DB-USER
              value: postgres
            - name: ENV
              value: prod
            - name: GRPC-SERVER-ADDRESS
              value: :54821
            - name: GRPC-SERVER-PORT
              value: "54821"
            - name: JWT-RAW-ACCESS-TTL
              value: 15m
            - name: JWT-RAW-ISSUER
              value: auth.service.local
            - name: JWT-RAW-PRIVATE-KEY
              value: config/private.pem
            - name: JWT-RAW-PUBLIC-KEY
              value: config/public.pem
            - name: JWT-RAW-REFRESH-PRIVATE-KEY
              value: config/private.pem
            - name: JWT-RAW-REFRESH-PUBLIC-KEY
              value: config/public.pem
            - name: JWT-RAW-REFRESH-TTL
              value: 168h
            - name: KAFKA-BROKERS
              value: kafka:9092
            - name: KAFKA-TOPIC
              value: user-events
            - name: NOTIFY-CLIENT-ADDRESS
              value: notify:54822
            - name: NOTIFY-CLIENT-BASE-DELAY
              value: 1s
            - name: NOTIFY-CLIENT-MAX-DELAY
              value: 5s
            - name: NOTIFY-CLIENT-MIN-CONNECT-TIMEOUT
              value: 5s
            - name: NOTIFY-CLIENT-MULTIPLIER
              value: "1.5"
            - name: TELEMETRY-ENVIRONMENT
              value: production
            - name: TELEMETRY-METRICS-PORT
              value: "10001"
            - name: TELEMETRY-SERVICE-NAME
              value: auth-service
            - name: TELEMETRY-SERVICE-VERSION
              value: 1.0.0
            - name: TELEMETRY-TRACE-ENDPOINT
              value: jaeger:4317
            - name: YANDEX-CLIENT-ID
              value: your-yandex-app-id
            - name: YANDEX-CLIENT-SECRET
              value: your-yandex-app-secret
            - name: YANDEX-REDIRECT-URL
              value: https://your-domain.com/auth/yandex/callback
          image: ghcr.io/netscrawler/restaurant-is-auth:latest
          name: auth-service
          ports:
            - containerPort: 54821
              protocol: TCP
            - containerPort: 10001
              protocol: TCP
      restartPolicy: Always
