apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: gate
  name: gate
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: gate
    spec:
      containers:
        - env:
            - name: AUTH-JWT-SECRET
              value: your-secret-key
            - name: SERVER-PORT
              value: "8080"
            - name: SERVICE-AUTH-HOST
              value: auth-service
            - name: SERVICE-AUTH-PORT
              value: "54821"
            - name: SERVICE-MENU-HOST
              value: menu-service
            - name: SERVICE-MENU-PORT
              value: "50052"
            - name: SERVICE-NOTIFY-HOST
              value: notify
            - name: SERVICE-NOTIFY-PORT
              value: "54822"
            - name: SERVICE-ORDER-HOST
              value: order-service
            - name: SERVICE-ORDER-PORT
              value: "50051"
            - name: SERVICE-USER-HOST
              value: user-service
            - name: SERVICE-USER-PORT
              value: "50045"
            - name: TELEMETRY-ENVIRONMENT
              value: production
            - name: TELEMETRY-METRICS-PORT
              value: "10002"
            - name: TELEMETRY-SERVICE-NAME
              value: gate
            - name: TELEMETRY-SERVICE-VERSION
              value: 1.0.0
            - name: TELEMETRY-TRACE-ENDPOINT
              value: jaeger:4317
          image: ghcr.io/netscrawler/restaurant-is-gate:latest
          name: gate
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 10002
              protocol: TCP
      restartPolicy: Always
