apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: grafana
    spec:
      containers:
        - env:
            - name: GF-AUTH-ANONYMOUS-ENABLED
              value: "true"
            - name: GF-AUTH-ANONYMOUS-ORG-ROLE
              value: Admin
          image: grafana/grafana:11.2.2
          name: grafana
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
