apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: kafka
    spec:
      containers:
        - env:
            - name: KAFKA-ADVERTISED-LISTENERS
              value: PLAINTEXT://kafka:9092
            - name: KAFKA-BROKER-ID
              value: "1"
            - name: KAFKA-DEFAULT-REPLICATION-FACTOR
              value: "1"
            - name: KAFKA-GROUP-INITIAL-REBALANCE-DELAY-MS
              value: "0"
            - name: KAFKA-NUM-PARTITIONS
              value: "1"
            - name: KAFKA-OFFSETS-TOPIC-REPLICATION-FACTOR
              value: "1"
            - name: KAFKA-ZOOKEEPER-CONNECT
              value: zookeeper:2181
          image: confluentinc/cp-kafka:7.5.0
          name: kafka
          ports:
            - containerPort: 9092
              protocol: TCP
      restartPolicy: Always
