apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: loki
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: loki
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: loki
    spec:
      containers:
        - args:
            - -config.file=/etc/loki/loki-config.yaml
          image: grafana/loki:3.2.1
          name: loki
          ports:
            - containerPort: 3100
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/loki/loki-config.yaml
              name: loki-cm0
              subPath: loki-config.yaml
            - mountPath: /loki
              name: loki-data
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: loki-config.yaml
                path: loki-config.yaml
            name: loki-cm0
          name: loki-cm0
        - name: loki-data
          persistentVolumeClaim:
            claimName: loki-data
