apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: menu-service
  name: menu-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: menu-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: menu-service
    spec:
      containers:
        - env:
            - name: DB-HOST
              value: menu-db
            - name: DB-NAME
              value: menu
            - name: DB-PASSWORD
              value: postgres
            - name: DB-POOL-MAX-CONN
              value: "20"
            - name: DB-POOL-MAX-CONN-LIFETIME
              value: 2h
            - name: DB-PORT
              value: "5434"
            - name: DB-SSL-MODE
              value: disable
            - name: DB-TYPE
              value: postgres
            - name: DB-USER
              value: postgres
            - name: ENV
              value: prod
            - name: GRPC-SERVER-ADDRESS
              value: localhost
            - name: GRPC-SERVER-PORT
              value: "50052"
            - name: MINIO-ACCESS-KEY
              value: minioadmin
            - name: MINIO-BUCKET
              value: images
            - name: MINIO-ENDPOINT
              value: minio:9000
            - name: MINIO-SECRET-KEY
              value: minioadmin
            - name: MINIO-URL-EXPIRY
              value: 15m
            - name: MINIO-USE-SSL
              value: "false"
            - name: TELEMETRY-ENVIRONMENT
              value: production
            - name: TELEMETRY-METRICS-PORT
              value: "10003"
            - name: TELEMETRY-SERVICE-NAME
              value: menu-service
            - name: TELEMETRY-SERVICE-VERSION
              value: 1.0.0
            - name: TELEMETRY-TRACE-ENDPOINT
              value: jaeger:4317
          image: ghcr.io/netscrawler/restaurant-is-menu-service:latest
          name: menu-service
          ports:
            - containerPort: 50052
              protocol: TCP
            - containerPort: 10003
              protocol: TCP
      restartPolicy: Always
