apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: menu-db
  name: menu-db
spec:
  ports:
    - name: "5434"
      port: 5434
      targetPort: 5434
  selector:
    io.kompose.service: menu-db
