apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: menu-db-replica
  name: menu-db-replica
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: menu-db-replica
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: menu-db-replica
    spec:
      containers:
        - args:
            - postgres
            - -c
            - port=5434
            - -c
            - wal-level=logical
          env:
            - name: POSTGRES-DB
              value: menu
            - name: POSTGRES-PASSWORD
              value: postgres
            - name: POSTGRES-USER
              value: postgres
          image: postgres:latest
          livenessProbe:
            exec:
              command:
                - pg-isready -U postgres -p 5434
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 5
          name: menu-db-replica
          ports:
            - containerPort: 5434
              protocol: TCP
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: menu-db-replica-cm0
              readOnly: true
            - mountPath: /var/lib/postgresql/data
              name: menu-postgres-data-replica
      restartPolicy: Always
      volumes:
        - configMap:
            name: menu-db-replica-cm0
          name: menu-db-replica-cm0
        - name: menu-postgres-data-replica
          persistentVolumeClaim:
            claimName: menu-postgres-data-replica
