apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: metabase
  name: metabase
spec:
  ports:
    - name: "3030"
      port: 3030
      targetPort: 3000
  selector:
    io.kompose.service: metabase
