apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: metabase
  name: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: metabase
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: metabase
    spec:
      containers:
        - env:
            - name: MB-DB-DBNAME
              value: metabase
            - name: MB-DB-HOST
              value: metabase-db
            - name: MB-DB-PASS
              value: metabase123
            - name: MB-DB-PORT
              value: "5438"
            - name: MB-DB-TYPE
              value: postgres
            - name: MB-DB-USER
              value: metabase
            - name: MB-METRICS-ENABLED
              value: "true"
          image: metabase/metabase:latest
          name: metabase
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
