apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: metabase-db
  name: metabase-db
spec:
  ports:
    - name: "5438"
      port: 5438
      targetPort: 5438
  selector:
    io.kompose.service: metabase-db
