apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: order-service
  name: order-service
spec:
  ports:
    - name: "50051"
      port: 50051
      targetPort: 50051
    - name: "10005"
      port: 10005
      targetPort: 10005
  selector:
    io.kompose.service: order-service
