apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: promtail
  name: promtail
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: promtail
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: promtail
    spec:
      containers:
        - args:
            - -config.file=/etc/promtail/promtail-config.yaml
          image: grafana/promtail:3.2.1
          name: promtail
          volumeMounts:
            - mountPath: /tmp
              name: promtail-cm0
            - mountPath: /etc/promtail/promtail-config.yaml
              name: promtail-cm1
              subPath: promtail-config.yaml
            - mountPath: /var/lib/docker/containers
              name: promtail-claim2
              readOnly: true
      restartPolicy: Always
      volumes:
        - configMap:
            name: promtail-cm0
          name: promtail-cm0
        - configMap:
            items:
              - key: promtail-config.yaml
                path: promtail-config.yaml
            name: promtail-cm1
          name: promtail-cm1
        - name: promtail-claim2
          persistentVolumeClaim:
            claimName: promtail-claim2
            readOnly: true
