apiVersion: v1
data:
  setup-subscription.sh: |
    #!/bin/bash

    # Ждём, пока Postgres точно запустится и начнёт слушать TCP
    until pg-isready -h menu-db -p 5434 -U postgres; do
      echo "Waiting for PostgreSQL to be ready..."
      sleep 1
    done

    # Проверка, есть ли уже подписка
    psql -U postgres -d menu -tc "SELECT 1 FROM pg-subscription WHERE subname = 'menu-subscription'" | grep -q 1 || \
    psql -U postgres -d menu -c "CREATE SUBSCRIPTION menu-subscription CONNECTION 'host=menu-db port=5434 user=replicator password=replicator-password dbname=menu' PUBLICATION menu-publication;"
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: subscription-setup-menu
  name: subscription-setup-menu-cm0
