apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: subscription-setup-user
  name: subscription-setup-user
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: subscription-setup-user
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-env.yaml -o k8s
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: subscription-setup-user
    spec:
      containers:
        - command:
            - bash
            - /setup-subscription.sh
          env:
            - name: PGPASSWORD
              value: replicator-password
          image: postgres:17
          name: subscription-setup-user
          volumeMounts:
            - mountPath: /setup-subscription.sh
              name: subscription-setup-user-cm0
              readOnly: true
              subPath: setup-subscription.sh
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: setup-subscription.sh
                path: setup-subscription.sh
            name: subscription-setup-user-cm0
          name: subscription-setup-user-cm0
