apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: user-postgres-data-replica
  name: user-postgres-data-replica
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
