FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build \
    -trimpath \
    -ldflags="-s -w -buildid= -extldflags=-static" \
    -buildvcs=false \
    -o menu ./cmd/menu

FROM gcr.io/distroless/static-debian12

WORKDIR /menu

COPY --from=builder /app/menu .

COPY --from=builder /app/config ./config

# Если нужны сертификаты (например, mTLS, HTTPS)
# COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

EXPOSE 54823

CMD ["./menu"]
