FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build \
    -trimpath \
    -ldflags="-s -w -buildid= -extldflags=-static" \
    -buildvcs=false \
    -o user ./cmd/user

FROM gcr.io/distroless/static-debian12

WORKDIR /user

COPY --from=builder /app/user .

# Если нужны сертификаты (например, mTLS, HTTPS)
# COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

EXPOSE 50045

CMD ["./user"]
